
import turtle as tur
def rectangle(color):
    turt.begin_fill()
    turt.fillcolor(color)
    for i in range(2):
        turt.forward(400)
        turt.right(90)
        turt.forward(100)
        turt.right(90)
    turt.end_fill()

turt=tur.Turtle()
tur.screensize(900,600)
tur.title("Happy republic day")
turt.up()
turt.pensize(4)
turt.goto(0,-300)
turt.down()
turt.goto(0,400)
rectangle("orange")
turt.goto(0,300)
turt.forward(200)
turt.color("blue")
turt.circle(-50)
turt.setheading(270)
turt.forward(50)
turt.setheading(0)
for i in range(24):
    turt.forward(45)
    turt.bk(45)
    turt.left(15)
turt.setheading(90)
turt.forward(50)
turt.setheading(0)
turt.color("black")
turt.forward(200)
turt.right(90)
turt.forward(100)
turt.right(90)
turt.forward(400)
turt.right(90)
turt.forward(100)
turt.right(90)
turt.goto(0,200)
rectangle("green")
# 
text = tur.Turtle() 
text.color("orange") 
text.penup() 
text.setposition(-100,170) 
text.write("Happy Republic day ", font=("Apple Chancery", 30, "bold"), align="right") 
text.setposition(-140,140) 
text.color("yellow") 
text.write("To all of you", font=("Avenir", 21, "bold"), align="right") 
# text.color("black") 
# text.write("from", font=("Apple Chancery", 20, "bold"), align="right") 
text.hideturtle() 
tur.done()